### ISSUE TITLE
Wrong parent, when duplicated on multisite

### ISSUE THREAD

**Issue by Pfeifakopf** [doublethreedigital/duplicator#12]
## Steps to reproduce

When you duplicate an entry on a multisite, you can choose, on which site it should be duplicated. The duplicated has the root as parent and you have to move it to the right position. 

## Expected behaviour

It would be better, if the parent would be the same from the source entry. 

## Environment information

**Statamic version:** 3.0.20

**PHP version:** 7.4

**Operating System:**
- [ ] MacOS
- [x] Linux
- [ ] Windows

**Comment by damcclean** [comment]
Thanks for reporting! I'll get to this at some point, hopefully this week.

**Comment by damcclean** [comment]
Just tagged a new release which means the same parent as the initial entry will be used when the new duplicated entry is created.

Released in [v1.2.0](https://github.com/doublethreedigital/duplicator/releases/tag/v1.2.0)
