### ISSUE TITLE
Local i18n file issue

### ISSUE THREAD

**Issue by thisJerem** [doublethreedigital/duplicator#18]
Hi Duncan, thank you the addon work well, but I have an issue with Statamic 3.0.45,  adding a messages.php with localized FR data do not work. 

![image](https://user-images.githubusercontent.com/1255528/110832167-4be87780-829b-11eb-9578-46de0587881c.png)

![image](https://user-images.githubusercontent.com/1255528/110832566-be595780-829b-11eb-8850-84450aa8c2a9.png)
I tried to erase the default EN local but it didn't work either.

## How to reproduce
Install the plugin and change the local to FR, do not set the fallback to EN to get the token instead the i18n value.
...

## What I expected
To be able to erase the default en value.
...

## Environment
Statamic 3.0.45 Pro
Laravel 8.28.1
PHP 7.3.27
doublethreedigital/duplicator 1.2.3
rias/statamic-position-fieldtype 2.0.1
statamic/migrator dev-master
statamic/ssg 0.2.0

**Comment by duncanmcclean** [comment]
Hi there,

You'll first need to publish Duplicator's translation files, which you can do by running the following command. It will create a file in `resources/lang/vendor/en` I think.

```
php artisan vendor:publish --tag="duplicator-translations"
```

You should be able to copy that file to the same path, but with `fr` instead of `en` and try again.

**Comment by duncanmcclean** [comment]
In fact, scrap that, doesn't look like the translation publishing works 🤦‍♂️ 

Create a file at `resources/lang/vendor/duplicator/fr/messages.php`, with the following content:

```
<?php

return [
    'duplicate' => 'Duplicate',

    'duplicated_title' => ' (Duplicated)',

    'fields' => [
        'site' => [
            'instructions' => 'Where should this entry be duplicated?',
        ],
    ],
];
```

You should then be able to use your own translations. I'm open to any pull requests to this addon if you'd like to add translations for French.

**Comment by thisJerem** [comment]
Great it works ! :)

Thanks you Duncan !
I will do a PR but I'm not sure of this message fields:site:instructions because I don't know in which context it will be prompt, is this related to a multisite installation ?

**Comment by duncanmcclean** [comment]
> Great it works ! :)
> 
> Thanks you Duncan !
> I will do a PR but I'm not sure of this message fields:site:instructions because I don't know in which context it will be prompt, is this related to a multisite installation ?

Yeah, it shows in the modal that comes up when you duplicate an entry in a multisite environment. I'm closing this issue now as it's been fixed, I'll try and get some translation docs up on the `README.md` this weekend.
