### ISSUE TITLE
Add a setting to define the publishing status of the new entry

### ISSUE THREAD

**Issue by thisJerem** [doublethreedigital/duplicator#19]
When duplicate an entry, the duplicated one is auto-published, based on the current entry we want duplicate.
It could be great to add an option or a global settings to let us decide of the publishing status of the duplicate content.
A quick description of the feature you'd like to see implemented.

## How should it work?
In the settings of the addon, we could add a checkbox to enable or not the auto-publishing, and get the boolean value inside the Entry::make Class to update the publishing status of the new entry.

**Comment by duncanmcclean** [comment]
Released as part of [v1.2.5](https://github.com/doublethreedigital/duplicator/releases/tag/v1.2.5). Thanks for the feature request!

**Comment by thisJerem** [comment]
Hi Duncan ! Thanks you for adding this feature this is great !
After publishing the config file et set to false the default published value, it seems to no take it.
I get always only a published to true.

I upgraded your addon,
php artisan vendor:publish --tag="duplicator-config"
Set to false inside the config/duplicator file
Clear all cache

Statamic 3.0.46 Pro
Laravel 8.32.1
PHP 7.4.16
doublethreedigital/duplicator 1.2.5
rias/statamic-position-fieldtype 2.0.1
statamic/migrator dev-master
statamic/ssg 0.2.0

**Comment by duncanmcclean** [comment]
> Hi Duncan ! Thanks you for adding this feature this is great !
> After publishing the config file et set to false the default published value, it seems to no take it.
> I get always only a published to true.
> 
> I upgraded your addon,
> php artisan vendor:publish --tag="duplicator-config"
> Set to false inside the config/duplicator file
> Clear all cache
> 
> Statamic 3.0.46 Pro
> Laravel 8.32.1
> PHP 7.4.16
> doublethreedigital/duplicator 1.2.5
> rias/statamic-position-fieldtype 2.0.1
> statamic/migrator dev-master
> statamic/ssg 0.2.0

I'll take a look now. fyi: I've created a new issue for this, as it's a bug: #21
