### ISSUE TITLE
Default publish state setting not working

### ISSUE THREAD

**Issue by duncanmcclean** [doublethreedigital/duplicator#21]
Hi Duncan ! Thanks you for adding this feature this is great !
After publishing the config file et set to false the default published value, it seems to no take it.
I get always only a published to true.

I upgraded your addon,
php artisan vendor:publish --tag="duplicator-config"
Set to false inside the config/duplicator file
Clear all cache

Statamic 3.0.46 Pro
Laravel 8.32.1
PHP 7.4.16
doublethreedigital/duplicator 1.2.5
rias/statamic-position-fieldtype 2.0.1
statamic/migrator dev-master
statamic/ssg 0.2.0

_Originally posted by @thisJerem in https://github.com/doublethreedigital/duplicator/issues/19#issuecomment-799600955_

**Comment by duncanmcclean** [comment]
Hmm, this seems to be working fine for me... here's a [quick screencast](https://www.loom.com/share/fa9f01e0cccb45bb9d893a8e1ec5499f) I recorded.

**Comment by thisJerem** [comment]
Hum stupid me ! :)
I had forgot to clear config with php please config:clear
It works pretty well, thanks you again Duncan !

**Comment by duncanmcclean** [comment]
No worries, have a nice day!
