### ISSUE TITLE
Test Fail with "Target class [config] does not exist."

### ISSUE THREAD

**Issue by dagy304** [doublethreedigital/duplicator#23]
Hello,

on version 1.2.5 the new duplicator.php config file was added.
Since then i cant run any phpunit tests because i get the error "Target class [config] does not exist."
If i remove the handleConfig function inside the ServiceProvider i still get the error.
Only if i delete the config file as well, do my Tests work.

Regards Thorben

**Comment by duncanmcclean** [comment]
Hey, I'm not 100% sure what causes this issue. I had this issue on another project recently (not Duplicator related I dont think). In the meantime, until I have a proper look, try adding this to your `TestCase`.

```php
public function tearDown(): void
    {
        // Destroy the $app
        if ($this->app) {
            $this->callBeforeApplicationDestroyedCallbacks();

            $this->app = null;
        }

       // Call parent teardown
       parent::tearDown();
    }
```

**Comment by dagy304** [comment]
Thanks, that worked!
Looking forward to the fix.

**Comment by duncanmcclean** [comment]
Just tagged a release which will fix the issue. It's not the nicest of solutions but it'll do for the time being. I think it might be a Statamic bug.

**Comment by duncanmcclean** [comment]
In the end, this did turn out to be a Statamic bug, statamic/cms#3435 which will be fixed in the next release. Once it's tagged, I'll remove my hotfix in here 👍
