### ISSUE TITLE
Duplicating taxonomies

### ISSUE THREAD

**Issue by 4kets** [doublethreedigital/duplicator#24]
I have created a taxonomy field which has more than the usual "title" and "slug" fields in the blueprint but now we cant duplicate the other taxonomies.

## What would you like to see added?
A way to duplicate taxonomies

## Is there a workaround you can use in the meantime?
Just redoing it everytime

**Comment by duncanmcclean** [comment]
I'll need to check again but I think I tried to do this originally and it wouldn't let me add a button into the taxonomy terms listing.

**Comment by duncanmcclean** [comment]
Ooops, turns out I was wrong. It's totally possible and I've just tagged a release with it: [v1.3.0](https://github.com/doublethreedigital/duplicator/releases/tag/v1.3.0).

**Comment by 4kets** [comment]
allright thank you
