### ISSUE TITLE
Let know the duplicated entry that it has been duplicated

### ISSUE THREAD

**Issue by thisJerem** [doublethreedigital/duplicator#27]
## What would you like to see added?
It would be really great to add a field like ```duplicated: true``` to the duplicated entry to let us do some adjustments or whatever guards actions based on eventListener action.
We can see it like a hidden watermark saved to the entry.

For exemple, I have a collection type with a lot of relational fields, some are taxonomy which I would to keep but some are very specific to the original entry and I would like to remove those relational values when the entry is duplicated.

In the DuplicateEntryAction.php we could add this line 65 :
```
$entry = Entry::make()
                        ->collection($item->collection())
                        ->blueprint($item->blueprint()->handle())
                        ->locale(isset($values['site']) ? $values['site'] : $item->locale())
                        ->published(config('duplicator.defaults.published', $item->published()))
                        ->slug($itemTitleAndSlug['slug'])
                        ->data($item->data()->merge([
                            'title' => $itemTitleAndSlug['title'],
                            'duplicated' => true
                        ]));
```

## Is there a workaround you can use in the meantime?
Despite make a fork of your addon no :(

What do you think about it ?

**Comment by duncanmcclean** [comment]
Released in [v1.3.3](https://github.com/doublethreedigital/duplicator/releases/tag/v1.3.3) - hopefully it works for you!
