### ISSUE TITLE
duplicate to multisite

### ISSUE THREAD

**Issue by EikeBierman** [doublethreedigital/duplicator#37]
### Bug Description

I have created a new project, installed the duplicator and https://statamic.dev/multi-site#overview created a multisite with it. 
Now when I want to duplicate the home page for one page, it still copies it for all pages.

my sites.php:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sites
    |--------------------------------------------------------------------------
    |
    | Each site should have root URL that is either relative or absolute. Sites
    | are typically used for localization (eg. English/French) but may also
    | be used for related content (eg. different franchise locations).
    |
    */

    'sites' => [
        'german' => [
            'name' => 'Deutschland',
            'locale' => 'de',
            'url' => env('APP_URL').'/',
        ],
        'switzerland' => [
            'name' => 'Schweiz',
            'locale' => 'ch',
            'url' => env('APP_URL').'ch/',
        ],
        'france' => [
            'name' => 'Frankreich',
            'locale' => 'en_US',
            'url' => env('APP_URL').'fr/',
        ],
        'italy' => [
            'name' => 'Italien',
            'locale' => 'en_US',
            'url' => env('APP_URL').'it/',
        ],
        'uk' => [
            'name' => 'England',
            'locale' => 'en_US',
            'url' => env('APP_URL').'en/',
        ],
    ],
];
```

### Steps to reproduce

1. create new statamic project
2. install duplucator
3. create sites with php please multisite 
4. insert sites in sites.php
5. try to duplicate home.md in german to switzerland.
5.1 choose switzerland in the modal
6. Problem: home is now in all lands ( switzerland, france, italy, uk)

### Environment

```
Statamic 3.2.33 Pro
Laravel 8.83.1
PHP 8.0.11
doublethreedigital/duplicator 2.1.0
```

**Comment by duncanmcclean** [comment]
Thanks for reporting! 

I don't have a test multisite handy so I'll need to block out some time, hopefully later this week, to create one & reproduce the issue.

**Comment by duncanmcclean** [comment]
Just had a chance to look into this.

I'm only able to replicate this issue if I have [propagation](https://statamic.dev/tips/localizing-entries#propagation) enabled on the collection I'm duplicating on - which is to be expected, any entries you create in a collection will be 'propagated' to all other sites.

I'm going to close this issue. If you don't have propagation enabled and are still seeing this issue, please create a fresh site, reproduce the issue and upload it to GitHub so I can take a further look. Thanks!
