### ISSUE TITLE
Duplicate a form

### ISSUE THREAD

**Issue by freshface** [doublethreedigital/duplicator#38]
### What would you like to see added?

To duplicate a form thru the control panel

### Is there a workaround you can use in the meantime?

To do it manually

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Thanks for the feature request! Unfortunately, Statamic doesn't allow for adding 'custom actions' to the Forms listing table, which we'd need in order for this to be possible.

I'll open a feature request on Statamic's side after work today.

**Comment by freshface** [comment]
Sweet!
