### ISSUE TITLE
Ignore certain fields

### ISSUE THREAD

**Issue by wesort** [doublethreedigital/duplicator#39]
### What would you like to see added?

**Desired:** The ability to **not** duplicate certain fields.

**Usecase**: We're using [Uuid](https://statamic.com/addons/aryeh-raber/uuid) to generate [human readable entry ID's](https://github.com/aryehraber/statamic-uuid/issues/12) for a field called `archive_uuid`. These supplement the {s} `id` and are used as a segment in the `slug`. When an entry is duplicated, I'd like a config option to not duplicate this field as Uuid will generate a new/unique value. As it's used in the URL, the entry won't save again after duplication with an error on slug field: `This URI has already been taken.` This is not _entirely_ true as the `slug` is not actually used, but rather that the `archive_uuid` value is not unique. The `archive_uuid` field is used across three collections and I have wondered while writing this if this extra config would need to be collection/taxonomy specific.

### Is there a workaround you can use in the meantime?

In the meantime, I've set the `archive_uuid` field to be `read_only: false` but ideally this would be set to `read_only: true` to ensure authors do not tamper with it. 

With this workaround authors can: duplicate an entry > clear the `archive_uuid` field > save the entry > Uuid will generate a new value.

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
Released in [v2.2.0](https://github.com/doublethreedigital/duplicator/releases/tag/v2.2.0)! 🚀
