### ISSUE TITLE
Multisite duplicate all sites

### ISSUE THREAD

**Issue by Hesesses** [doublethreedigital/duplicator#41]
### What would you like to see added?

When duplicating an entry i would like to get all language versions to be duplicated.

For example I have a page in english and finnish.

I duplicate english page

the result is english page is duplicated and finnish version is not.

### Is there a workaround you can use in the meantime?

I need to manually copy paste .md files and change origins

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Released in [v2.2.0](https://github.com/doublethreedigital/duplicator/releases/tag/v2.2.0)! 🚀

**Comment by Hesesses** [comment]
Thank you for making the fix, it now creates pages for all sites.

It sill has one bug.

For example I have a page in English and Finnish.

1. duplicate the page for all sites.
2. it creates a page with English and Finnish versions
3. the english version has everything as it should, but the Finnish version is a copy of english version, not a Finnish version

**Comment by duncanmcclean** [comment]
I’m open to a pull request to fix the issue - I won’t have time to look into it for a while.
