### ISSUE TITLE
Question if anyone else has had this error: PHP Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by Pixney-William** [doublethreedigital/duplicator#5]
This is more a question than an issue, if anyone else has had this error installing it?

![image](https://user-images.githubusercontent.com/31292231/88458159-4d8c3900-ce8c-11ea-858e-9afbb9302270.png)

Obv i can increase memory, but it feels kind of weird this happens.

**Comment by damcclean** [comment]
I'm not sure why that's happening, I've personally never had an issues with it (I don't think)

In the meantime you can increase Composer's memory, either in your `php.ini` or just for this command, like (remember to change the path of PHP to the one on your machine, you can usually find it by running `which php`):

```
php -d memory_limit=-1 /usr/local/bin/composer require doublethreedigital/duplicator
```

I'll try and replicate this at some point, sorry for the issue!

**Comment by Pixney-William** [comment]
Don't be sorry:) Temp set the memory like that works fine so no worries. Just trying to figure out why it is needed. But otherwise everything else works fine!

**Comment by damcclean** [comment]
Yeah, sometimes I get it when installing packages too, most of the time I just use an alias I have which allows Composer to use max memory. i'll test it at some point to see if I get the same thing, sometimes things like this happen for some people and not others.

**Comment by Pixney-William** [comment]
Its does for sure.

**Comment by damcclean** [comment]
Just tried to replicate the issue but I was unsuccessful. I think these issues are different per machine depending on the way PHP is configured. I'm going to close the issue now but if someone runs into this in the future, feel free to re-open the issue.
