### ISSUE TITLE
Duplicate for replicator and grid

### ISSUE THREAD

**Issue by Pfeifakopf** [doublethreedigital/duplicator#7]
Is it possible to add the duplicate possibility for replicator and grid sets?

**Comment by damcclean** [comment]
I'll have to have a look whenever I can find the time.

**Comment by damcclean** [comment]
You seem to be able to duplicate entries with Grid and Replicator fieldtypes in just fine.

However, I think you're asking if it's possible to add a 'Duplicate' button inside the Grid fieldtype? If so, that's not really something this addon can do as we can't make changes to any of the built-in fieldtypes.

It would be something that would be better placed as an issue on the [statamic/ideas](https://github.com/statamic/ideas) repo. I also feel like that sort of functionality would be better suited as part of the fieldtype anyway.
